# Generated by Django 5.1 on 2024-08-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.CharField(max_length=50)),
                ('school_admin_first_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_admin',
            fields=[
                ('school_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('School_admin_name', models.CharField(max_length=255)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
            ],
        ),
    ]
