# Generated by Django 5.1 on 2024-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_admin_username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_admin_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
