# Generated by Django 5.1 on 2024-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0002_school_school_admin_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_admin',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='school_admin',
            old_name='School_admin_name',
            new_name='school_admin_name',
        ),
    ]
