# Generated by Django 5.1 on 2024-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0003_rename_school_id_school_admin_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_admin_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
