# Generated by Django 5.1 on 2024-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0004_school_school_admin_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_admin',
            name='school',
        ),
        migrations.AddField(
            model_name='school_admin',
            name='school_admin_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school_admin',
            name='school_admin_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
