# Generated by Django 5.1 on 2024-08-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0005_remove_school_admin_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_admin',
            name='school_admin_name',
        ),
        migrations.AddField(
            model_name='school_admin',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school'),
        ),
    ]
