# Generated by Django 5.1 on 2024-08-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0006_remove_school_admin_school_admin_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_admin',
        ),
    ]
