# Generated by Django 5.1 on 2024-08-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0007_delete_school_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_admin',
            fields=[
                ('school_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_admin_first_name', models.CharField(max_length=50, null=True)),
                ('school_admin_last_name', models.CharField(max_length=50, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
            ],
        ),
    ]
