# Generated by Django 5.1 on 2024-08-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0008_school_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_admin',
            name='school_admin_username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
