# Generated by Django 5.1 on 2024-08-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0010_employee_teacher_class_teacher_warden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_teacher',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
