# Generated by Django 5.1 on 2024-08-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0011_rename_teacher_class_teacher_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('admission_number', models.CharField(max_length=20, null=True)),
                ('roll_number', models.IntegerField(null=True)),
                ('parents_number', models.CharField(max_length=15, null=True)),
                ('parents_email', models.EmailField(max_length=40, null=True)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.class_teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_authentication.warden')),
            ],
        ),
    ]
