# Generated by Django 5.1 on 2024-09-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0016_notification_student_notification_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
