# Generated by Django 5.1 on 2024-09-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0017_remove_notification_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher'),
        ),
    ]
