# Generated by Django 5.1 on 2024-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0019_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='absence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
