# Generated by Django 5.1 on 2024-09-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0023_leavereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereason',
            name='parent_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.notification'),
        ),
    ]
