# Generated by Django 5.1 on 2024-09-06 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0024_leavereason_parent_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotification',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.leavereason'),
        ),
    ]
