# Generated by Django 5.1 on 2024-09-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0025_teachernotification_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('school_admin_username', models.CharField(max_length=15, null=True)),
                ('class_name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
            ],
        ),
    ]
