# Generated by Django 5.1 on 2024-09-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0026_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
