# Generated by Django 5.1 on 2024-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0029_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('marks_obtained', models.CharField(blank=True, max_length=10, null=True)),
                ('out_of', models.CharField(blank=True, max_length=10, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher')),
            ],
        ),
    ]
