# Generated by Django 5.1 on 2024-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0030_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
