# Generated by Django 5.1 on 2024-09-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0031_exam_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
