# Generated by Django 5.1 on 2024-09-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0032_remove_subject_exam_remove_subject_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=25)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('marks_obtained', models.CharField(blank=True, max_length=10, null=True)),
                ('out_of', models.CharField(blank=True, max_length=10, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.subject')),
            ],
        ),
    ]
