# Generated by Django 5.1 on 2024-09-19 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0034_assignment_assignmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentnotification',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.subject'),
        ),
        migrations.AddField(
            model_name='assignmentnotification',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher'),
        ),
    ]
