# Generated by Django 5.1 on 2024-09-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0035_assignmentnotification_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentnotification',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school'),
        ),
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.assignment')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.student')),
            ],
        ),
    ]
