# Generated by Django 5.1 on 2024-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0037_alter_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('absent', 'Absent Notification'), ('assignment', 'Assignment Notification')], default='absent', max_length=20),
        ),
    ]
