# Generated by Django 5.1 on 2024-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0038_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
