# Generated by Django 5.1 on 2024-09-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0039_studentassignmentsubmission_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignmentsubmission',
            old_name='is_read',
            new_name='is_submitted',
        ),
    ]
