# Generated by Django 5.1 on 2024-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0040_rename_is_read_studentassignmentsubmission_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='submission_date',
            field=models.DateField(),
        ),
    ]
