# Generated by Django 5.1 on 2024-09-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0041_alter_studentassignmentsubmission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='class_assigned',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='division_assigned',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.student'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='submission_date',
            field=models.DateField(blank=True),
        ),
    ]
