# Generated by Django 5.1 on 2024-09-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0042_alter_studentassignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
