# Generated by Django 5.1 on 2024-09-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0043_alter_studentassignmentsubmission_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
