# Generated by Django 5.1 on 2024-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0044_assignment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Warden', 'Warden')], default='Teacher', max_length=20),
        ),
    ]
