# Generated by Django 5.1 on 2024-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0047_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
