# Generated by Django 5.1 on 2024-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0048_event_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
