# Generated by Django 5.1 on 2024-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0053_eventbanner_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
