# Generated by Django 5.1 on 2024-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0054_eventnotification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='type',
            field=models.CharField(default='event', max_length=20),
        ),
    ]
