# Generated by Django 5.1 on 2024-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0056_remove_school_admin_school_admin_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_admin',
            name='school_admin_username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
