# Generated by Django 5.1 on 2024-10-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0061_remove_assignmentnotification_date_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=15, null=True)),
                ('class_assigned', models.CharField(max_length=15, null=True)),
                ('division_assigned', models.CharField(max_length=15, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(max_length=15, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.subject')),
            ],
        ),
    ]
