# Generated by Django 5.1 on 2024-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0062_examtimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetable',
            name='subject',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
