# Generated by Django 5.1 on 2024-10-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0063_alter_examtimetable_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableNotification',
            fields=[
                ('timetable_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=15, null=True)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.exam')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
            ],
        ),
    ]
