# Generated by Django 5.1 on 2024-10-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0064_timetablenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablenotification',
            name='type',
            field=models.CharField(default='timetable', max_length=20),
        ),
    ]
