# Generated by Django 5.1 on 2024-10-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_authentication', '0065_timetablenotification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_authentication.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.CharField(max_length=10)),
                ('class_and_division', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='setup_authentication.teachertimetable')),
            ],
            options={
                'unique_together': {('timetable', 'period_number')},
            },
        ),
    ]
